import type { TechnologySkill } from '@/types/skills.types'

export const professionalSkills: TechnologySkill[] = [
  { iconSlug: 'html5', displayName: 'HTML5', hexColorCode: 'E34F26' },
  { iconSlug: 'css', displayName: 'CSS3', hexColorCode: '1572B6' },
  { iconSlug: 'javascript', displayName: 'JavaScript', hexColorCode: 'F7DF1E' },
  { iconSlug: 'typescript', displayName: 'TypeScript', hexColorCode: '3178C6' },
  { iconSlug: 'react', displayName: 'React', hexColorCode: '61DAFB' },
  { iconSlug: 'nextdotjs', displayName: 'Next.js', hexColorCode: '000000', isDarkThemed: true },
  { iconSlug: 'tailwindcss', displayName: 'Tailwind CSS', hexColorCode: '06B6D4' },
  { iconSlug: 'shadcnui', displayName: 'Shadcn UI', hexColorCode: '000000', isDarkThemed: true },
  { iconSlug: 'radixui', displayName: 'Radix UI', hexColorCode: '000000', isDarkThemed: true },
  { iconSlug: 'framer', displayName: 'Motion', hexColorCode: '0055FF' },
  { iconSlug: 'nodedotjs', displayName: 'Node.js', hexColorCode: '339933' },
  { iconSlug: 'express', displayName: 'Express', hexColorCode: '000000', isDarkThemed: true },
  { iconSlug: 'zod', displayName: 'Zod', hexColorCode: '3E67B1' },
  { iconSlug: 'vitest', displayName: 'Vitest', hexColorCode: '6E9F18' },
  { iconSlug: 'jest', displayName: 'Jest', hexColorCode: 'C21325' },
  { iconSlug: 'testinglibrary', displayName: 'Testing Library', hexColorCode: 'E33332' },
  { iconSlug: 'vite', displayName: 'Vite', hexColorCode: '646CFF' },
  { iconSlug: 'firebase', displayName: 'Firebase', hexColorCode: 'FFCA28' },
  { iconSlug: 'vercel', displayName: 'Vercel', hexColorCode: '000000', isDarkThemed: true },
  { iconSlug: 'git', displayName: 'Git', hexColorCode: 'F05032' },
  { iconSlug: 'github', displayName: 'GitHub', hexColorCode: '181717', isDarkThemed: true },
]
